data:
  name: edge
  crop_type: rand_resize_crop
  img_folder: '/data/zhoucaixia/Dataset/edge_stylegan2'
  augment_horizontal_flip: True
  batch_size: 1
  num_workers: 8

trainer:
  gradient_accumulate_every: 16
  lr: !!float 5e-5
  min_lr: !!float 5e-6
  train_num_steps: 5000
  save_and_sample_every: 100
  enable_resume: False
  log_freq: 100
  results_folder: "/data/zhoucaixia/workspace/DiffusionEdge/training/sd_generative_multiselect4_minigpt4_grant_no01_ordistance_normalization"
  amp: False
  fp16: False
  resume_milestone: 0
  test_before: True
  ema_update_after_step: 100
  ema_update_every: 10